name: Build and Rsync to Remote Server

on:
  push:
    branches:
      - staging  # Or whichever branch you want this to run on

jobs:
  build-and-sync:
    runs-on: ubuntu-latest

    steps:
      # Check out the repo
      - name: Checkout repository
        uses: actions/checkout@v2
      
      # Setup Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # Or your desired version
      
      # Install dependencies and build
      - name: Install dependencies and build
        run: |
          cd cms/web/app/themes/full-swing
          yarn
          yarn build
      
      # Setup SSH and Rsync to remote
      - name: Setup SSH and Rsync to remote
        env:
          DEPLOY_KEY: ${{ secrets.FULLSWINGSPORTSNEW }}
          DESTINATION: ploi@3.135.63.128:/home/ploi/stg.shop.fullswingsports.com/public/wp-content/themes/fullswing
          PLUGIN_DESTINATION: ploi@3.135.63.128:/home/ploi/stg.shop.fullswingsports.com/public/wp-content/plugins
        run: |
          sudo apt-get update
          sudo apt-get install -y ssh rsync

          echo "$DEPLOY_KEY" > deploy_key
          chmod 600 deploy_key

          # Rsync theme
          rsync -avz --delete --exclude 'node_modules' -e 'ssh -i deploy_key -o StrictHostKeyChecking=no' ./cms/web/app/themes/full-swing/ $DESTINATION

          # Rsync plugins
          rsync -avz --delete -e 'ssh -i deploy_key -o StrictHostKeyChecking=no' ./cms/web/app/mu-plugins/ $PLUGIN_DESTINATION

          # Reload PHP
          ssh -i deploy_key ploi@3.135.63.128 -t "echo '' | sudo -S service php8.4-fpm reload"

          rm -f deploy_key
